language: ruby
rvm:
  - 2.7.1
cache: bundler
branches:
  only:
  - main
notifications:
  email:
    recipients:
      - ramonsantos.pe@gmail.com
    on_success: change
    on_failure: always
script:
  - bundle install --jobs=3 --retry=3
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local_dir: ./site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
