# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ramon Santos
email: ramonsantos.pe@gmail.com
description: Blog sobre desenvolvimento
tagline: Blog sobre desenvolvimento
lang: pt_BR
baseurl: "/"
url: "https://ramonsantos.github.io"
permalink: "blog/:title:output_ext"

# Build settings
theme: shine-on-you-crazy-diamond-theme
# remote_theme: ramonsantos/shine-on-you-crazy-diamond-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-target-blank
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
menu:
  - home:
    label: Home
    path: '/'
  - blog:
    label: Blog
    path: '/blog/'
  - about:
    label: Sobre
    path: '/about/'

disqus:
  shortname: ramon-santos

google_analytics: UA-82053881-1

twitter:
  card: summary
  username: ramonsantos_dev
  picture: "/ramon-santos.png"

facebook:
  app_id: 122740845026539
  admins: CjHweHcsUQm

author:
  twitter: ramonsantos_dev

defaults:
  - scope:
      path: ""
    values:
      image: /ramon-santos.png

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  slug_mode: "latin"
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'

pagination:
  enabled: true
  debug: false
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 3
    after: 3
